#!/usr/bin/env python3

import subprocess
import sys


def main():
	if len(sys.argv) < 2:
		print("Please provide a regex search term.")
		return 1
	search_term = sys.argv[1]
	
	terms = subprocess.check_output(["apt-cache", "search", search_term])
	program = subprocess.check_output(["fzf"], input=terms).decode("utf-8")
	subprocess.run(["sudo", "apt-get", "install", program.split(" - ")[0]])
	
	return 0

if __name__ == '__main__':
	exit(main())
