#!/usr/bin/env python

# Create shims that allow flatpak apps to be executed from the command line by only using the end part of the packge name.
# ie com.valvesoftware.Steam -> steam
# Requires "~/.flatpak-shims" to be added to $PATH.

import subprocess
import os
import stat
import shutil

DIRS = [
    os.path.expanduser("~/.local/share/flatpak/exports/share/applications/"),
    "/var/lib/flatpak/exports/share/applications/",
]
SHIM_PATH = "/home/jake/.flatpak-shims"


def main():
    try:
        os.mkdir(SHIM_PATH)
    except:
        shutil.rmtree(SHIM_PATH)
        os.mkdir(SHIM_PATH)
    
    # All the executable apps are in these folders
    for dir in DIRS:
        for file in os.listdir(dir):
            if "mimeinfo.cache" in file:
                continue
            full_app_name = file.removesuffix(".desktop")
            app_name = full_app_name.split(".")[2].lower()

            file = f"{SHIM_PATH}/{app_name}"

            with open(file, "w") as f:
                f.write(f"""
                    #!/bin/sh
                    exec flatpak run {full_app_name}
                """)
    
            st = os.stat(file)
            os.chmod(file, st.st_mode | stat.S_IEXEC)

if __name__ == '__main__':
    main()
