#!/usr/bin/env python

import os
import sys

def main():
	if len(sys.argv) < 2:
		print("Missing filepath")
		exit(1)

	filename = sys.argv[1]

	*path, name = filename.split("/")

	filepath = '/'.join(path)

	os.system(f"mkdir -p {filepath}")
	os.system(f"touch {filepath}/{name}")

main()
