#!/bin/sh

if [ -z $1 ]; then
	echo "Please provide a mark."
	exit 1
fi

marks="$HOME/.local/state/marks/$1"

if [ -f $marks ]; then
    echo $(cat $marks)
else
	echo "Could not find a mark for $1" 1>&2
	exit
fi
