#!/usr/bin/env python

import os
import sys
import subprocess

def main():
	if len(sys.argv) == 1:
		print("rename path/to/file new_name")
		exit(1)
	
	if sys.argv[1] == "--help":
		print("rename path/to/file new_name")

	if len(sys.argv) < 3:
		print("Missing arguments")
		print("rename path/to/file new_name")
		exit(1)

	*path, filename = sys.argv[1].split("/")
	filepath = '/'.join(path)

	subprocess.run(["mv", sys.argv[1], f"{filepath}/{sys.argv[2]}"])


if __name__ == "__main__":
	main()
